[theme]
base = "light"
primaryColor = "#C9A961"
backgroundColor = "#F8F8F8"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0A0A0A"
font = "sans serif"

[server]
headless = true
runOnSave = true
maxUploadSize = 50

[browser]
gatherUsageStats = false
